# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Cadiz
email: cadiz.christopher@gmail.com
description: >
  Android, iOS, Web developer from Winnipeg, Canada
logo: "/assets/images/icon.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cadiz.ca" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Chris Cadiz'
bio: >
  I'm a software developer based in Winnipeg, Canada and I currently work at Arclabs.
  I have a deep interest in learning, and entrepreneurship, and technology.
author_image: "/assets/images/chriscadiz.jpg"
twitter_username: chris_cadiz
github_username:  chriscadiz
permalink: :slug

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-redirect-from
